### ISSUE TITLE
webpack: Failed to compile

### ISSUE THREAD

**Issue by haruelrovix** [tegila/material_base#3]
Hi, how to make it running on localhost? I tried to clone this, `yarn && yarn start`, got following error:

```bash
  1:19  error  Unable to resolve path to module '../../../redux-store-mongodb/index'  import/no-unresolved
  1:19  error  Missing file extension for "../../../redux-store-mongodb/index"        import/extensions
```

What's the content of `'../../../redux-store-mongodb/index'` file?

Thanks.

**Comment by tegila** [comment]
Sorry, the module was outdated. I just fixed it now and it's ready.

Don't forget to init the submodules:

git pull && git submodule init && git submodule update && git submodule status
cd libs/mongo.io/client ; yarn

;)

**Comment by haruelrovix** [comment]
Great @tegila 👍 

Even though it throws many error, at least it can be running locally.

![image](https://user-images.githubusercontent.com/17120764/43118708-417cd45c-8f3d-11e8-9617-98bda486e8b2.png)

I came across here from fr********.com btw.

**Comment by tegila** [comment]
Hi @haruelrovix;

This error is because the frontend wasnt able to connect to the backend. 

The backend testnet was running some minutes ago and I think it’s related with your distance to the server or something else out of code.

I imaginated you come from there, btw now is 2:35am here, on the morning I fix more problems on this project.

But it’s only a boilerplate, you can add a view cart.js and go on without any concern about the other routes. 

Thank you for your issue anyway I’ll consider that as a diferencial.

See ya
